# Staging k3s manifest (example)
# Deploys Frappe, ERPNext, Agriculture app, yam_agri_core, DB, ingress, storage

---
apiVersion: v1
kind: Namespace
metadata:
  name: yam-agri-staging
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frappe
  namespace: yam-agri-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frappe
  template:
    metadata:
      labels:
        app: frappe
    spec:
      containers:
      - name: frappe
        image: frappe/erpnext
        ports:
        - containerPort: 8000
        env:
        - name: SITE_NAME
          value: staging.local
        - name: INSTALL_APPS
          value: erpnext,agriculture
        volumeMounts:
        - mountPath: /home/frappe/frappe-bench/sites
          name: frappe-sites
      volumes:
      - name: frappe-sites
        persistentVolumeClaim:
          claimName: frappe-sites-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agriculture-app
  namespace: yam-agri-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agriculture-app
  template:
    metadata:
      labels:
        app: agriculture-app
    spec:
      containers:
      - name: agriculture-app
        image: yam_agri_core/agriculture_app:latest
        env:
        - name: FRAPPE_URL
          value: http://frappe.yam-agri-staging.svc.cluster.local:8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yam-agri-core
  namespace: yam-agri-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yam-agri-core
  template:
    metadata:
      labels:
        app: yam-agri-core
    spec:
      containers:
      - name: yam-agri-core
        image: yam_agri_core/yam_agri_core:latest
        env:
        - name: FRAPPE_URL
          value: http://frappe.yam-agri-staging.svc.cluster.local:8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: yam-agri-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: postgres:15
        env:
        - name: POSTGRES_DB
          value: yam_agri
        - name: POSTGRES_USER
          value: yam
        - name: POSTGRES_PASSWORD
          value: yam_pw
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-data
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: db-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: frappe
  namespace: yam-agri-staging
spec:
  selector:
    app: frappe
  ports:
  - port: 8000
    targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: agriculture-app
  namespace: yam-agri-staging
spec:
  selector:
    app: agriculture-app
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: yam-agri-core
  namespace: yam-agri-staging
spec:
  selector:
    app: yam-agri-core
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: yam-agri-staging
spec:
  selector:
    app: db
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: yam-agri-ingress
  namespace: yam-agri-staging
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: staging.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frappe
            port:
              number: 8000
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frappe-sites-pvc
  namespace: yam-agri-staging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data-pvc
  namespace: yam-agri-staging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
