# Deprecated staging manifest
#
# This file is retained for backward compatibility with historical docs.
# Phase 8 execution now uses modular manifests under:
#   environments/staging/manifests/
#
# Preferred apply path:
#   kubectl apply -k environments/staging/manifests
#
# If secrets are required, generate them first:
#   environments/staging/scripts/generate-secrets.sh

apiVersion: v1
kind: Namespace
metadata:
  name: yam-agri-staging
