name: compose
services:
  backend:
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      MARIADB_ROOT_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    image: frappe/erpnext:v16.5.0
    networks:
      frappe_network: null
    volumes:
      - type: volume
        source: sites
        target: /home/frappe/frappe-bench/sites
        volume: {}
      - type: volume
        source: logs
        target: /home/frappe/frappe-bench/logs
        volume: {}
  configurator:
    command:
      - ls
      - "-1"
      - apps
    entrypoint:
      - bash
      - -c
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
      SOCKETIO_PORT: "9000"
    image: frappe/erpnext:v16.5.0
    networks:
      frappe_network: null
    volumes:
      - type: volume
        source: sites
        target: /home/frappe/frappe-bench/sites
        volume: {}
      - type: volume
        source: logs
        target: /home/frappe/frappe-bench/logs
        volume: {}
  create-site:
    command:
      - set
      - -e
    entrypoint:
      - bash
      - -c
    image: frappe/erpnext:v16.5.0
    networks:
      frappe_network: null
    volumes:
      - type: volume
        source: sites
        target: /home/frappe/frappe-bench/sites
        volume: {}
      - type: volume
        source: logs
        target: /home/frappe/frappe-bench/logs
        volume: {}
  db:
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
    environment:
      MARIADB_ROOT_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    healthcheck:
      test:
        - CMD-SHELL
        - mysqladmin ping -h localhost --password=admin
      interval: 1s
      retries: 20
    image: mariadb:10.6
    networks:
      frappe_network: null
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/mysql
        volume: {}
  frontend:
    command:
      - nginx-entrypoint.sh
    depends_on:
      websocket:
        condition: service_started
        required: true
    environment:
      BACKEND: backend:8000
      CLIENT_MAX_BODY_SIZE: 50m
      FRAPPE_SITE_NAME_HEADER: frontend
      PROXY_READ_TIMEOUT: "120"
      SOCKETIO: websocket:9000
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"
    image: frappe/erpnext:v16.5.0
    networks:
      frappe_network: null
    ports:
      - mode: ingress
        target: 8080
        published: "8080"
        protocol: tcp
    volumes:
      - type: volume
        source: sites
        target: /home/frappe/frappe-bench/sites
        volume: {}
      - type: volume
        source: logs
        target: /home/frappe/frappe-bench/logs
        volume: {}
  queue-long:
    command:
      - bench
      - worker
      - --queue
      - long,default,short
    environment:
      FRAPPE_REDIS_CACHE: redis://redis-cache:6379
      FRAPPE_REDIS_QUEUE: redis://redis-queue:6379
    image: frappe/erpnext:v16.5.0
    networks:
      frappe_network: null
    volumes:
      - type: volume
        source: sites
        target: /home/frappe/frappe-bench/sites
        volume: {}
      - type: volume
        source: logs
        target: /home/frappe/frappe-bench/logs
        volume: {}
  queue-short:
    command:
      - bench
      - worker
      - --queue
      - short,default
    environment:
      FRAPPE_REDIS_CACHE: redis://redis-cache:6379
      FRAPPE_REDIS_QUEUE: redis://redis-queue:6379
    image: frappe/erpnext:v16.5.0
    networks:
      frappe_network: null
    volumes:
      - type: volume
        source: sites
        target: /home/frappe/frappe-bench/sites
        volume: {}
      - type: volume
        source: logs
        target: /home/frappe/frappe-bench/logs
        volume: {}
  redis-cache:
    image: redis:6.2-alpine
    networks:
      frappe_network: null
  redis-queue:
    image: redis:6.2-alpine
    networks:
      frappe_network: null
    volumes:
      - type: volume
        source: redis-queue-data
        target: /data
        volume: {}
  scheduler:
    command:
      - bench
      - schedule
    image: frappe/erpnext:v16.5.0
    networks:
      frappe_network: null
    volumes:
      - type: volume
        source: sites
        target: /home/frappe/frappe-bench/sites
        volume: {}
      - type: volume
        source: logs
        target: /home/frappe/frappe-bench/logs
        volume: {}
  websocket:
    command:
      - node
      - /home/frappe/frappe-bench/apps/frappe/socketio.js
    environment:
      FRAPPE_REDIS_CACHE: redis://redis-cache:6379
      FRAPPE_REDIS_QUEUE: redis://redis-queue:6379
    image: frappe/erpnext:v16.5.0
    networks:
      frappe_network: null
    volumes:
      - type: volume
        source: sites
        target: /home/frappe/frappe-bench/sites
        volume: {}
      - type: volume
        source: logs
        target: /home/frappe/frappe-bench/logs
        volume: {}
networks:
  frappe_network:
    name: compose_frappe_network
    driver: bridge
volumes:
  db-data:
    name: compose_db-data
  logs:
    name: compose_logs
  redis-queue-data:
    name: compose_redis-queue-data
  sites:
    name: compose_sites
