name: Bug Report
description: Report a bug or unexpected behaviour in the YAM Agri platform
title: "bug: "
labels: ["bug", "needs-triage"]
assignees:
  - YasserAKareem
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug. Please fill in as much detail as possible so we can reproduce and fix it quickly.

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Which environment did you observe this in?
      options:
        - Dev (Docker Compose)
        - Staging
        - Production
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Affected area
      description: Which part of the system is affected?
      options:
        - Lot / Traceability
        - QCTest / Certificate
        - ScaleTicket / Weight
        - Transfer (split/merge/blend)
        - Observation / Sensor
        - EvidencePack
        - Nonconformance / CAPA
        - Complaint
        - Site / StorageBin / Device
        - Infrastructure / Docker
        - Authentication / Permissions
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clear and concise description of the bug.
      placeholder: "When I do X, Y happens instead of Z."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Step-by-step instructions to reproduce the issue.
      placeholder: |
        1. Go to ...
        2. Click on ...
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behaviour
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs or screenshots
      description: Paste any error messages, stack traces, or attach screenshots.
      render: shell

  - type: checkboxes
    id: security
    attributes:
      label: Security check
      options:
        - label: This bug report does NOT contain passwords, tokens, or other secrets.
          required: true
